# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  adhocrg: 'dylanadhocpoker'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  enabled: false

- task: BatchScript@1
  inputs:
    filename: '$(Build.SourcesDirectory)\src\PokerLeagueManager.UI.Web\BuildAngular.bat'
  enabled: false
    
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  enabled: false

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  enabled: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\'
    Contents: |
      **\*.dacpac
      **\*.Commands.WebApi.zip
      **\*.Events.WebApi.zip
      **\*.Queries.WebApi.zip
      **\*.UI.Web.zip
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\PokerLeagueManager.Utilities\bin\$(buildConfiguration)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Utility'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\deploy'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\deploy'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'WorkshopAzure'
    subscriptionName: 'e16d929e-2ebf-4445-805e-c032ef6c4559'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(adhocrg)'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)\deploy\Azure ARM\ArmTemplate.json'
    overrideParameters: '-appname $(adhocrg)'
    deploymentMode: 'Incremental'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'WorkshopAzure'
    appType: 'webApp'
    WebAppName: '$(adhocrg)-commands'
    packageForLinux: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.Commands.WebApi.zip'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'WorkshopAzure'
    appType: 'webApp'
    WebAppName: '$(adhocrg)-events'
    packageForLinux: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.Events.WebApi.zip'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'WorkshopAzure'
    appType: 'webApp'
    WebAppName: '$(adhocrg)-queries'
    packageForLinux: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.Queries.WebApi.zip'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'WorkshopAzure'
    appType: 'webApp'
    WebAppName: '$(adhocrg)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.UI.Web.zip'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'WorkshopAzure'
    AuthenticationType: 'server'
    ServerName: '$(adhocrg).database.windows.net'
    DatabaseName: 'Events'
    SqlUsername: 'dylan'
    SqlPassword: 'P2ssw0rd'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.DB.EventStore.dacpac'
    IpDetectionMethod: 'AutoDetect'
    AdditionalArguments: '/p:CreateNewDatabase=true'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'WorkshopAzure'
    AuthenticationType: 'server'
    ServerName: '$(adhocrg).database.windows.net'
    DatabaseName: 'Queries'
    SqlUsername: 'dylan'
    SqlPassword: 'P2ssw0rd'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.ArtifactStagingDirectory)\PokerLeagueManager.DB.QueryStore.dacpac'
    IpDetectionMethod: 'AutoDetect'
    AdditionalArguments: '/p:CreateNewDatabase=true'

- task: CmdLine@2
  inputs:
    script: 'PokerLeagueManager.Utilities.exe CreateEventSubscriber $(adhocrg).database.windows.net Events dylan P2ssw0rd http://$(adhocrg)-events.azurewebsites.net'
    workingDirectory: '$(Build.ArtifactStagingDirectory)\Utility'

- task: CmdLine@2
  inputs:
    script: 'PokerLeagueManager.Utilities.exe GenerateSampleData http://$(adhocrg)-commands.azurewebsites.net 5'
    workingDirectory: '$(Build.ArtifactStagingDirectory)\Utility'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'WorkshopAzure'
    subscriptionName: 'e16d929e-2ebf-4445-805e-c032ef6c4559'
    action: 'DeleteRG'
    resourceGroupName: '$(adhocrg)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
